### ISSUE TITLE
asyncsafe fails to build on Ubuntu 14.04

### ISSUE THREAD

**Issue by briskycat** [dwks/asyncsafe#1]
$ make
gcc -Wall -Wextra  -Wno-unused-parameter test.c -o test
gcc -Wall -Wextra  -Wno-unused-parameter test2.c -o test2
gcc -Wall -Wextra  -O -shared -fPIC safe.c allow.c print.c elfmap.c plt.c resolve.s violation.c -o libasyncsafe.so -ldl
elfmap.c: In function ‘find_strtab’:
elfmap.c:88:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for(int i = 0; i < elf->header->e_shnum; i ++) {
     ^
elfmap.c:88:5: note: use option -std=c99 or -std=gnu99 to compile your code
elfmap.c: In function ‘find_got_and_plt’:
elfmap.c:105:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for(int i = 0; i < elf->header->e_shnum; i ++) {
     ^
plt.c: In function ‘reset_plt_entries’:
plt.c:44:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for(size_t i = 0; i < plt_count; i ++) {
     ^
plt.c:44:5: note: use option -std=c99 or -std=gnu99 to compile your code
plt.c: In function ‘restore_plt_entries’:
plt.c:74:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for(size_t i = 0; i < plt_count; i ++) {
     ^
violation.c: In function ‘asyncsafe_violation’:
violation.c:34:10: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
     write(STDERR_FILENO, message, p - message);
          ^
make: **\* [libasyncsafe.so] Error 1

After adding -std=c99 the following warning remains:

$ make
gcc -std=c99 -Wall -Wextra  -Wno-unused-parameter test.c -o test
gcc -std=c99 -Wall -Wextra  -Wno-unused-parameter test2.c -o test2
gcc -std=c99 -Wall -Wextra  -O -shared -fPIC safe.c allow.c print.c elfmap.c plt.c resolve.s violation.c -o libasyncsafe.so -ldl
violation.c: In function ‘asyncsafe_violation’:
violation.c:34:10: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
     write(STDERR_FILENO, message, p - message);

**Comment by dwks** [comment]
You are right that the code is written in C99. Try -std=gnu99 instead. With -std=c99, GCC constructors are not available.

**Comment by briskycat** [comment]
I just pulled the latest version where you apparently added the -std=gnu99 option. Now everything compiles without warnings but I get a segmentation fault with test:

$ make
gcc -std=gnu99 -Wall -Wextra -Wno-unused-result  -Wno-unused-parameter test.c -o test
gcc -std=gnu99 -Wall -Wextra -Wno-unused-result  -Wno-unused-parameter test2.c -o test2
gcc -std=gnu99 -Wall -Wextra -Wno-unused-result  -O -shared -fPIC safe.c allow.c print.c elfmap.c plt.c resolve.s violation.c -o libasyncsafe.so -ldl

$ ASYNCSAFE_LOGGING=1 LD_PRELOAD=./libasyncsafe.so ./test
getting ELF info for [/proc/36947/exe]
Segmentation fault (core dumped)

$ gdb ./test ./core 
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/.
Find the GDB manual and other documentation resources online at:
http://www.gnu.org/software/gdb/documentation/.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./test...(no debugging symbols found)...done.
[New LWP 36950]
Core was generated by `./test'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fdba93030cd in asyncsafe_init () from ./libasyncsafe.so
(gdb) bt
#0  0x00007fdba93030cd in asyncsafe_init () from ./libasyncsafe.so
#1  0x00007fdba930313a in sigaction () from ./libasyncsafe.so
#2  0x00007fdba93031c7 in signal () from ./libasyncsafe.so
#3  0x0000000000400658 in main ()
(gdb)

**Comment by dwks** [comment]
There are two link-time flags that affect how the PLT is generated: `-z relro` and `-z now`. It appears that `-z now` is the problem here, as it causes the .rela.plt section to not be included in the executable (which the code uses at the moment). Ubuntu may have `-z now` as the default although the default is normally the opposite, `-z lazy`, on other systems. You can override this by passing `-z lazy` to ld, or rather `-Wl,-z,lazy` to GCC. I pushed this as 4d9cdc6bd60e7242300051c13c68873cb8e062b7.

I also made sure asyncsafe is compatible with `-z relro` (make some pages read-only) and it seems to be. I wrote a patch that makes it read/write just in case -- let me know if you need this. You can also experiment with `-z norelro`. For more info see http://security.stackexchange.com/questions/24444/what-is-the-most-hardened-set-of-options-for-gcc-compiling-c-c

**Comment by briskycat** [comment]
Thanks,
-Wl,-z,lazy didn't help, unfortunately. I added debugging info so that it is clearer where the segmentation fault happens:

Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fadba2500cd in asyncsafe_init () at safe.c:26
26      plt_count = elf.plt_got->sh_size;
(gdb) bt
#0  0x00007fadba2500cd in asyncsafe_init () at safe.c:26
#1  0x00007fadba25013a in sigaction (signum=signum@entry=10, act=act@entry=0x7ffc8f44d1b0, oldact=oldact@entry=0x7ffc8f44d250) at safe.c:69
#2  0x00007fadba2501c7 in signal (signum=10, handler=0x40060d <good>) at safe.c:62
#3  0x0000000000400658 in main () at test.c:14
(gdb) 

None of the linker flags you mentioned above seems to change this.

**Comment by dwks** [comment]
OK, time to try the relro patch. I've pushed it to the `relro` branch. Also, can you paste the output of `readelf -hS test` ? I'm wondering if maybe the .plt.got section doesn't exist...

**Comment by briskycat** [comment]
The output (without the patch):

`$ readelf -hS test
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x400520
  Start of program headers:          64 (bytes into file)
  Start of section headers:          4496 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         9
  Size of section headers:           64 (bytes)
  Number of section headers:         30
  Section header string table index: 27

Section Headers:
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [ 0]                   NULL             0000000000000000  00000000
       0000000000000000  0000000000000000           0     0     0
  [ 1] .interp           PROGBITS         0000000000400238  00000238
       000000000000001c  0000000000000000   A       0     0     1
  [ 2] .note.ABI-tag     NOTE             0000000000400254  00000254
       0000000000000020  0000000000000000   A       0     0     4
  [ 3] .note.gnu.build-i NOTE             0000000000400274  00000274
       0000000000000024  0000000000000000   A       0     0     4
  [ 4] .gnu.hash         GNU_HASH         0000000000400298  00000298
       000000000000001c  0000000000000000   A       5     0     8
  [ 5] .dynsym           DYNSYM           00000000004002b8  000002b8
       00000000000000a8  0000000000000018   A       6     1     8
  [ 6] .dynstr           STRTAB           0000000000400360  00000360
       0000000000000050  0000000000000000   A       0     0     1
  [ 7] .gnu.version      VERSYM           00000000004003b0  000003b0
       000000000000000e  0000000000000002   A       5     0     2
  [ 8] .gnu.version_r    VERNEED          00000000004003c0  000003c0
       0000000000000020  0000000000000000   A       6     1     8
  [ 9] .rela.dyn         RELA             00000000004003e0  000003e0
       0000000000000018  0000000000000018   A       5     0     8
  [10] .rela.plt         RELA             00000000004003f8  000003f8
       0000000000000090  0000000000000018   A       5    12     8
  [11] .init             PROGBITS         0000000000400488  00000488
       000000000000001a  0000000000000000  AX       0     0     4
  [12] .plt              PROGBITS         00000000004004b0  000004b0
       0000000000000070  0000000000000010  AX       0     0     16
  [13] .text             PROGBITS         0000000000400520  00000520
       00000000000001e2  0000000000000000  AX       0     0     16
  [14] .fini             PROGBITS         0000000000400704  00000704
       0000000000000009  0000000000000000  AX       0     0     4
  [15] .rodata           PROGBITS         0000000000400710  00000710
       0000000000000031  0000000000000000   A       0     0     4
  [16] .eh_frame_hdr     PROGBITS         0000000000400744  00000744
       0000000000000044  0000000000000000   A       0     0     4
  [17] .eh_frame         PROGBITS         0000000000400788  00000788
       0000000000000134  0000000000000000   A       0     0     8
  [18] .init_array       INIT_ARRAY       0000000000600e10  00000e10
       0000000000000008  0000000000000000  WA       0     0     8
  [19] .fini_array       FINI_ARRAY       0000000000600e18  00000e18
       0000000000000008  0000000000000000  WA       0     0     8
  [20] .jcr              PROGBITS         0000000000600e20  00000e20
       0000000000000008  0000000000000000  WA       0     0     8
  [21] .dynamic          DYNAMIC          0000000000600e28  00000e28
       00000000000001d0  0000000000000010  WA       6     0     8
  [22] .got              PROGBITS         0000000000600ff8  00000ff8
       0000000000000008  0000000000000008  WA       0     0     8
  [23] .got.plt          PROGBITS         0000000000601000  00001000
       0000000000000048  0000000000000008  WA       0     0     8
  [24] .data             PROGBITS         0000000000601048  00001048
       0000000000000010  0000000000000000  WA       0     0     8
  [25] .bss              NOBITS           0000000000601058  00001058
       0000000000000008  0000000000000000  WA       0     0     1
  [26] .comment          PROGBITS         0000000000000000  00001058
       000000000000002b  0000000000000001  MS       0     0     1
  [27] .shstrtab         STRTAB           0000000000000000  00001083
       0000000000000108  0000000000000000           0     0     1
  [28] .symtab           SYMTAB           0000000000000000  00001910
       0000000000000690  0000000000000018          29    45     8
  [29] .strtab           STRTAB           0000000000000000  00001fa0
       0000000000000279  0000000000000000           0     0     1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), l (large)
  I (info), L (link order), G (group), T (TLS), E (exclude), x (unknown)
  O (extra OS processing required) o (OS specific), p (processor specific)`

**Comment by briskycat** [comment]
The relro branch didn't work either:

`$ git checkout relro
Branch relro set up to track remote branch relro from origin.
Switched to a new branch 'relro'
$ make clean
rm -f test test2 libasyncsafe.so
$ make
gcc -std=gnu99 -Wall -Wextra -Wno-unused-result -Wl,-z,lazy  -Wno-unused-parameter test.c -o test
gcc -std=gnu99 -Wall -Wextra -Wno-unused-result -Wl,-z,lazy  -Wno-unused-parameter test2.c -o test2
gcc -std=gnu99 -Wall -Wextra -Wno-unused-result -Wl,-z,lazy  -O -shared -fPIC safe.c allow.c print.c elfmap.c plt.c resolve.s violation.c -o libasyncsafe.so -ldl
$ ASYNCSAFE_LOGGING=1 LD_PRELOAD=./libasyncsafe.so ./test
getting ELF info for [/proc/29027/exe]
Segmentation fault (core dumped)
$ readelf -hS test
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x400520
  Start of program headers:          64 (bytes into file)
  Start of section headers:          4496 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         9
  Size of section headers:           64 (bytes)
  Number of section headers:         30
  Section header string table index: 27

Section Headers:
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [ 0]                   NULL             0000000000000000  00000000
       0000000000000000  0000000000000000           0     0     0
  [ 1] .interp           PROGBITS         0000000000400238  00000238
       000000000000001c  0000000000000000   A       0     0     1
  [ 2] .note.ABI-tag     NOTE             0000000000400254  00000254
       0000000000000020  0000000000000000   A       0     0     4
  [ 3] .note.gnu.build-i NOTE             0000000000400274  00000274
       0000000000000024  0000000000000000   A       0     0     4
  [ 4] .gnu.hash         GNU_HASH         0000000000400298  00000298
       000000000000001c  0000000000000000   A       5     0     8
  [ 5] .dynsym           DYNSYM           00000000004002b8  000002b8
       00000000000000a8  0000000000000018   A       6     1     8
  [ 6] .dynstr           STRTAB           0000000000400360  00000360
       0000000000000050  0000000000000000   A       0     0     1
  [ 7] .gnu.version      VERSYM           00000000004003b0  000003b0
       000000000000000e  0000000000000002   A       5     0     2
  [ 8] .gnu.version_r    VERNEED          00000000004003c0  000003c0
       0000000000000020  0000000000000000   A       6     1     8
  [ 9] .rela.dyn         RELA             00000000004003e0  000003e0
       0000000000000018  0000000000000018   A       5     0     8
  [10] .rela.plt         RELA             00000000004003f8  000003f8
       0000000000000090  0000000000000018   A       5    12     8
  [11] .init             PROGBITS         0000000000400488  00000488
       000000000000001a  0000000000000000  AX       0     0     4
  [12] .plt              PROGBITS         00000000004004b0  000004b0
       0000000000000070  0000000000000010  AX       0     0     16
  [13] .text             PROGBITS         0000000000400520  00000520
       00000000000001e2  0000000000000000  AX       0     0     16
  [14] .fini             PROGBITS         0000000000400704  00000704
       0000000000000009  0000000000000000  AX       0     0     4
  [15] .rodata           PROGBITS         0000000000400710  00000710
       0000000000000031  0000000000000000   A       0     0     4
  [16] .eh_frame_hdr     PROGBITS         0000000000400744  00000744
       0000000000000044  0000000000000000   A       0     0     4
  [17] .eh_frame         PROGBITS         0000000000400788  00000788
       0000000000000134  0000000000000000   A       0     0     8
  [18] .init_array       INIT_ARRAY       0000000000600e10  00000e10
       0000000000000008  0000000000000000  WA       0     0     8
  [19] .fini_array       FINI_ARRAY       0000000000600e18  00000e18
       0000000000000008  0000000000000000  WA       0     0     8
  [20] .jcr              PROGBITS         0000000000600e20  00000e20
       0000000000000008  0000000000000000  WA       0     0     8
  [21] .dynamic          DYNAMIC          0000000000600e28  00000e28
       00000000000001d0  0000000000000010  WA       6     0     8
  [22] .got              PROGBITS         0000000000600ff8  00000ff8
       0000000000000008  0000000000000008  WA       0     0     8
  [23] .got.plt          PROGBITS         0000000000601000  00001000
       0000000000000048  0000000000000008  WA       0     0     8
  [24] .data             PROGBITS         0000000000601048  00001048
       0000000000000010  0000000000000000  WA       0     0     8
  [25] .bss              NOBITS           0000000000601058  00001058
       0000000000000008  0000000000000000  WA       0     0     1
  [26] .comment          PROGBITS         0000000000000000  00001058
       000000000000002b  0000000000000001  MS       0     0     1
  [27] .shstrtab         STRTAB           0000000000000000  00001083
       0000000000000108  0000000000000000           0     0     1
  [28] .symtab           SYMTAB           0000000000000000  00001910
       0000000000000690  0000000000000018          29    45     8
  [29] .strtab           STRTAB           0000000000000000  00001fa0
       0000000000000279  0000000000000000           0     0     1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), l (large)
  I (info), L (link order), G (group), T (TLS), E (exclude), x (unknown)
  O (extra OS processing required) o (OS specific), p (processor specific)`

**Comment by dwks** [comment]
I fired up a 14.04 virtual machine. It turns out that it doesn't emit a `.plt.got` section with ld 2.24, even though a 16.04 machine with ld 2.26 and the same GCC does have this section. So, I changed the code to only rely on `.got.plt`. I'm not certain it's correct but please pull a0aae4fbc98550eb7570aabcec813e539e3da34d and test.

**Comment by briskycat** [comment]
Thanks a lot! At least the tests work now)

**Comment by dwks** [comment]
Great! If you have any issues on larger-scale programs just let me know.
